# Generated by Django 4.0.3 on 2023-05-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_user_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
