# Generated by Django 4.0.3 on 2023-05-11 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_studentprofile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecturer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_attendances', to='attendance.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(related_name='student_attendances', to='attendance.studentprofile'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='Raymond', max_length=250),
            preserve_default=False,
        ),
    ]
