# Generated by Django 4.0.3 on 2023-05-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_instructorattendance_studentattendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
    ]
