# Generated by Django 4.0.3 on 2023-05-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_programmecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('Continuing', 'Continuing'), ('Completed', 'Completed')], default='Continuing', max_length=20),
        ),
    ]
