# Generated by Django 4.0.3 on 2023-05-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_studentprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='Duration',
            field=models.CharField(choices=[('3', 'Three Years'), ('4', 'Four Years')], default=3, max_length=1),
            preserve_default=False,
        ),
    ]
