# Generated by Django 4.0.3 on 2023-05-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_programme_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='Duration',
            new_name='duration',
        ),
    ]
