# Generated by Django 4.0.3 on 2023-05-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_rename_duration_programme_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'date_enrolled', 'semester')},
        ),
    ]
