# Generated by Django 4.0.3 on 2023-05-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_programmecourse_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmecourse',
            old_name='course_type',
            new_name='requirement',
        ),
    ]
