# Generated by Django 4.0.3 on 2023-05-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_rename_course_type_programmecourse_requirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmecourse',
            old_name='requirement',
            new_name='status',
        ),
    ]
