# Generated by Django 4.0.3 on 2023-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_rename_requirement_programmecourse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='programmecourse',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
