# Generated by Django 4.0.3 on 2023-05-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_remove_course_semester_remove_course_year_of_study_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorattendance',
            old_name='lesson',
            new_name='attendance',
        ),
        migrations.RenameField(
            model_name='studentattendance',
            old_name='lesson',
            new_name='attendance',
        ),
    ]
