# Generated by Django 4.0.3 on 2023-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_remove_studentprofile_user_remove_user_programme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fingerprint_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fingerprint_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
