# Generated by Django 4.0.3 on 2023-07-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_studentprofile_fingerprint_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('lecturer', 'course')},
        ),
    ]
