# Generated by Django 4.0.3 on 2023-07-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day', 'course', 'start_time', 'end_time', 'venue')},
        ),
    ]
