# Generated by Django 4.0.3 on 2023-07-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='fingerprint_data',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
