# Generated by Django 4.0.3 on 2023-07-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_alter_studentprofile_fingerprint_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='fingerprint_data',
            field=models.TextField(unique=True),
        ),
    ]
